### ISSUE TITLE
I tried running your model and it was successful and tried matching with the output of the paper but I am still not able to figure out what it is giving as output? Can you explain what is the actual output?

### ISSUE THREAD

**Issue by anikashc** [mysbupt/KERN#2]

**Comment by mysbupt** [comment]
What do you mean by "output"? The model's prediction or the MAE/MAPE on the test data?

**Comment by anikashc** [comment]
Model's prediction. Like in the paper it is showing graphs for eg. FIG 6. Is it plotting something like that through this model as well?

**Comment by mysbupt** [comment]
The code for plotting the curves (shown in the paper) is not included in this repo. You can plot by yourself, here is the prediction https://github.com/mysbupt/KERN/blob/25323a089294c3b88ac28b3b25301cd567caab21/train.py#L175, which is the prediction for test data.

**Comment by mysbupt** [comment]
Also, the prediction will be dumped into files, which is this line of code: https://github.com/mysbupt/KERN/blob/25323a089294c3b88ac28b3b25301cd567caab21/train.py#L131
